
language: php
php:
  - nightly
  - 7.0
  

before_install:
  - composer self-update

install:
  - travis_retry composer install --prefer-source

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls

sudo: false